version: "3"

services:
  sixnode0:
    container_name: sixnode0
    image: "asia-southeast1-docker.pkg.dev/six-protocol/six-node-docker-repo/sixnode:${DOCKER_TAG:-4.0.3}"
    ports:
      - "26666-26667:26656-26657"
      - "8645-8646:8545-8546"
      - "9690-9691:9090-9091"
      - "1367:1317"
    volumes:
      - ./build/sixnode0/:/opt/build/six_home/
    command: bash ${COMMAND}.sh sixnode0
    environment:
      - TZ=Asia/Bangkok
    networks:
      localnet:
        ipv4_address: 10.10.0.2

  sixnode1:
    container_name: sixnode1
    image: "asia-southeast1-docker.pkg.dev/six-protocol/six-node-docker-repo/sixnode:${DOCKER_TAG:-4.0.3}"
    ports:
      - "26676-26677:26656-26657"
      - "8745-8746:8545-8546"
      - "9790-9791:9090-9091"
    volumes:
      - ./build/sixnode1/:/opt/build/six_home/
    command: bash ${COMMAND}.sh sixnode1
    environment:
      - TZ=Asia/Soul
    networks:
      localnet:
        ipv4_address: 10.10.0.3

  sixnode2:
    container_name: sixnode2
    image: "asia-southeast1-docker.pkg.dev/six-protocol/six-node-docker-repo/sixnode:${DOCKER_TAG:-4.0.3}"
    ports:
      - "26686-26687:26656-26657"
      - "8845-8846:8545-8546"
      - "9890-9891:9090-9091"
    volumes:
      - ./build/sixnode2/:/opt/build/six_home/
    command: bash ${COMMAND}.sh sixnode2
    environment:
      - TZ=America/New_York
    networks:
      localnet:
        ipv4_address: 10.10.0.4

  sixnode3:
    container_name: sixnode3
    image: "asia-southeast1-docker.pkg.dev/six-protocol/six-node-docker-repo/sixnode:${DOCKER_TAG:-4.0.3}"
    ports:
      - "26696-26697:26656-26657"
      - "8945-8946:8545-8546"
      - "9990-9991:9090-9091"
    volumes:
      - ./build/sixnode3/:/opt/build/six_home/
    command: bash ${COMMAND}.sh sixnode3
    environment:
      - TZ=Europe/London
    networks:
      localnet:
        ipv4_address: 10.10.0.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
