// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nftmngr/disable_virtual_schema.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type DisableVirtualSchemaProposal struct {
	Id                string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VirtualSchemaCode string                          `protobuf:"bytes,2,opt,name=virtualSchemaCode,proto3" json:"virtualSchemaCode,omitempty"`
	Registry          []*DisableVirtualSchemaRegistry `protobuf:"bytes,3,rep,name=registry,proto3" json:"registry,omitempty"`
	SubmitTime        time.Time                       `protobuf:"bytes,4,opt,name=submitTime,proto3,stdtime" json:"submitTime"`
	VotinStartTime    time.Time                       `protobuf:"bytes,5,opt,name=votinStartTime,proto3,stdtime" json:"votinStartTime"`
	VotingEndTime     time.Time                       `protobuf:"bytes,6,opt,name=votingEndTime,proto3,stdtime" json:"votingEndTime"`
}

func (m *DisableVirtualSchemaProposal) Reset()         { *m = DisableVirtualSchemaProposal{} }
func (m *DisableVirtualSchemaProposal) String() string { return proto.CompactTextString(m) }
func (*DisableVirtualSchemaProposal) ProtoMessage()    {}
func (*DisableVirtualSchemaProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2dd6dee3450cf76, []int{0}
}
func (m *DisableVirtualSchemaProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DisableVirtualSchemaProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DisableVirtualSchemaProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DisableVirtualSchemaProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableVirtualSchemaProposal.Merge(m, src)
}
func (m *DisableVirtualSchemaProposal) XXX_Size() int {
	return m.Size()
}
func (m *DisableVirtualSchemaProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableVirtualSchemaProposal.DiscardUnknown(m)
}

var xxx_messageInfo_DisableVirtualSchemaProposal proto.InternalMessageInfo

func (m *DisableVirtualSchemaProposal) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DisableVirtualSchemaProposal) GetVirtualSchemaCode() string {
	if m != nil {
		return m.VirtualSchemaCode
	}
	return ""
}

func (m *DisableVirtualSchemaProposal) GetRegistry() []*DisableVirtualSchemaRegistry {
	if m != nil {
		return m.Registry
	}
	return nil
}

func (m *DisableVirtualSchemaProposal) GetSubmitTime() time.Time {
	if m != nil {
		return m.SubmitTime
	}
	return time.Time{}
}

func (m *DisableVirtualSchemaProposal) GetVotinStartTime() time.Time {
	if m != nil {
		return m.VotinStartTime
	}
	return time.Time{}
}

func (m *DisableVirtualSchemaProposal) GetVotingEndTime() time.Time {
	if m != nil {
		return m.VotingEndTime
	}
	return time.Time{}
}

type VirtualSchemaDisableRequest struct {
	VirtualNftSchemaCode string `protobuf:"bytes,1,opt,name=virtualNftSchemaCode,proto3" json:"virtualNftSchemaCode,omitempty"`
}

func (m *VirtualSchemaDisableRequest) Reset()         { *m = VirtualSchemaDisableRequest{} }
func (m *VirtualSchemaDisableRequest) String() string { return proto.CompactTextString(m) }
func (*VirtualSchemaDisableRequest) ProtoMessage()    {}
func (*VirtualSchemaDisableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2dd6dee3450cf76, []int{1}
}
func (m *VirtualSchemaDisableRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VirtualSchemaDisableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VirtualSchemaDisableRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VirtualSchemaDisableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualSchemaDisableRequest.Merge(m, src)
}
func (m *VirtualSchemaDisableRequest) XXX_Size() int {
	return m.Size()
}
func (m *VirtualSchemaDisableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualSchemaDisableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualSchemaDisableRequest proto.InternalMessageInfo

func (m *VirtualSchemaDisableRequest) GetVirtualNftSchemaCode() string {
	if m != nil {
		return m.VirtualNftSchemaCode
	}
	return ""
}

type DisableVirtualSchemaRegistry struct {
	NftSchemaCode string         `protobuf:"bytes,1,opt,name=nftSchemaCode,proto3" json:"nftSchemaCode,omitempty"`
	Status        RegistryStatus `protobuf:"varint,2,opt,name=status,proto3,enum=thesixnetwork.sixprotocol.nftmngr.RegistryStatus" json:"status,omitempty"`
}

func (m *DisableVirtualSchemaRegistry) Reset()         { *m = DisableVirtualSchemaRegistry{} }
func (m *DisableVirtualSchemaRegistry) String() string { return proto.CompactTextString(m) }
func (*DisableVirtualSchemaRegistry) ProtoMessage()    {}
func (*DisableVirtualSchemaRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2dd6dee3450cf76, []int{2}
}
func (m *DisableVirtualSchemaRegistry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DisableVirtualSchemaRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DisableVirtualSchemaRegistry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DisableVirtualSchemaRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableVirtualSchemaRegistry.Merge(m, src)
}
func (m *DisableVirtualSchemaRegistry) XXX_Size() int {
	return m.Size()
}
func (m *DisableVirtualSchemaRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableVirtualSchemaRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_DisableVirtualSchemaRegistry proto.InternalMessageInfo

func (m *DisableVirtualSchemaRegistry) GetNftSchemaCode() string {
	if m != nil {
		return m.NftSchemaCode
	}
	return ""
}

func (m *DisableVirtualSchemaRegistry) GetStatus() RegistryStatus {
	if m != nil {
		return m.Status
	}
	return RegistryStatus_PENDING
}

type ActiveDislabeVirtualSchemaProposal struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *ActiveDislabeVirtualSchemaProposal) Reset()         { *m = ActiveDislabeVirtualSchemaProposal{} }
func (m *ActiveDislabeVirtualSchemaProposal) String() string { return proto.CompactTextString(m) }
func (*ActiveDislabeVirtualSchemaProposal) ProtoMessage()    {}
func (*ActiveDislabeVirtualSchemaProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2dd6dee3450cf76, []int{3}
}
func (m *ActiveDislabeVirtualSchemaProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActiveDislabeVirtualSchemaProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActiveDislabeVirtualSchemaProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActiveDislabeVirtualSchemaProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveDislabeVirtualSchemaProposal.Merge(m, src)
}
func (m *ActiveDislabeVirtualSchemaProposal) XXX_Size() int {
	return m.Size()
}
func (m *ActiveDislabeVirtualSchemaProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveDislabeVirtualSchemaProposal.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveDislabeVirtualSchemaProposal proto.InternalMessageInfo

func (m *ActiveDislabeVirtualSchemaProposal) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type InactiveDisableVirtualSchemaProposal struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *InactiveDisableVirtualSchemaProposal) Reset()         { *m = InactiveDisableVirtualSchemaProposal{} }
func (m *InactiveDisableVirtualSchemaProposal) String() string { return proto.CompactTextString(m) }
func (*InactiveDisableVirtualSchemaProposal) ProtoMessage()    {}
func (*InactiveDisableVirtualSchemaProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2dd6dee3450cf76, []int{4}
}
func (m *InactiveDisableVirtualSchemaProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InactiveDisableVirtualSchemaProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InactiveDisableVirtualSchemaProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InactiveDisableVirtualSchemaProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InactiveDisableVirtualSchemaProposal.Merge(m, src)
}
func (m *InactiveDisableVirtualSchemaProposal) XXX_Size() int {
	return m.Size()
}
func (m *InactiveDisableVirtualSchemaProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_InactiveDisableVirtualSchemaProposal.DiscardUnknown(m)
}

var xxx_messageInfo_InactiveDisableVirtualSchemaProposal proto.InternalMessageInfo

func (m *InactiveDisableVirtualSchemaProposal) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*DisableVirtualSchemaProposal)(nil), "thesixnetwork.sixprotocol.nftmngr.DisableVirtualSchemaProposal")
	proto.RegisterType((*VirtualSchemaDisableRequest)(nil), "thesixnetwork.sixprotocol.nftmngr.VirtualSchemaDisableRequest")
	proto.RegisterType((*DisableVirtualSchemaRegistry)(nil), "thesixnetwork.sixprotocol.nftmngr.DisableVirtualSchemaRegistry")
	proto.RegisterType((*ActiveDislabeVirtualSchemaProposal)(nil), "thesixnetwork.sixprotocol.nftmngr.ActiveDislabeVirtualSchemaProposal")
	proto.RegisterType((*InactiveDisableVirtualSchemaProposal)(nil), "thesixnetwork.sixprotocol.nftmngr.InactiveDisableVirtualSchemaProposal")
}

func init() {
	proto.RegisterFile("nftmngr/disable_virtual_schema.proto", fileDescriptor_d2dd6dee3450cf76)
}

var fileDescriptor_d2dd6dee3450cf76 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x9b, 0x16, 0xaa, 0xe1, 0x69, 0x95, 0xb0, 0x76, 0xa8, 0xca, 0x94, 0x96, 0xa8, 0x87,
	0x1e, 0xc0, 0x11, 0xe5, 0xcf, 0x15, 0x31, 0xca, 0x61, 0x08, 0xf1, 0x27, 0x9d, 0x38, 0xc0, 0x61,
	0x72, 0x1a, 0xd7, 0xb5, 0x48, 0xe2, 0x62, 0xbf, 0x29, 0xdd, 0xa7, 0x60, 0x57, 0xbe, 0xd1, 0x8e,
	0x3b, 0x72, 0x02, 0xd4, 0x7e, 0x11, 0x84, 0x13, 0xa3, 0x06, 0x22, 0xad, 0xbd, 0x39, 0xef, 0xeb,
	0xe7, 0x17, 0x3f, 0xef, 0x63, 0xa3, 0x7e, 0x3a, 0x85, 0x24, 0xe5, 0xca, 0x8f, 0x84, 0xa6, 0x61,
	0xcc, 0xce, 0x16, 0x42, 0x41, 0x46, 0xe3, 0x33, 0x3d, 0x99, 0xb1, 0x84, 0x92, 0xb9, 0x92, 0x20,
	0xf1, 0x5d, 0x98, 0x31, 0x2d, 0x96, 0x29, 0x83, 0x2f, 0x52, 0x7d, 0x22, 0x5a, 0x2c, 0x4d, 0x7d,
	0x22, 0x63, 0x52, 0xe8, 0x3b, 0x47, 0x16, 0x54, 0x05, 0xe8, 0x1c, 0x72, 0xc9, 0xa5, 0x59, 0xfa,
	0x7f, 0x56, 0x45, 0xb5, 0xcb, 0xa5, 0xe4, 0x31, 0xf3, 0xcd, 0x57, 0x98, 0x4d, 0x7d, 0x10, 0x09,
	0xd3, 0x40, 0x93, 0x79, 0xbe, 0xc1, 0xfb, 0xd6, 0x40, 0x47, 0xa3, 0xfc, 0x60, 0xef, 0x73, 0xec,
	0xd8, 0x50, 0xdf, 0x2a, 0x39, 0x97, 0x9a, 0xc6, 0xb8, 0x85, 0xea, 0x22, 0x6a, 0x3b, 0x3d, 0x67,
	0x70, 0x2b, 0xa8, 0x8b, 0x08, 0xdf, 0x43, 0xb7, 0x17, 0x9b, 0x1b, 0x9f, 0xcb, 0x88, 0xb5, 0xeb,
	0xa6, 0xfd, 0x7f, 0x03, 0x7f, 0x44, 0x7b, 0x8a, 0x71, 0xa1, 0x41, 0x9d, 0xb7, 0x1b, 0xbd, 0xc6,
	0x60, 0x7f, 0xf8, 0x94, 0x5c, 0xeb, 0x94, 0x54, 0x1d, 0x28, 0x28, 0x30, 0xc1, 0x5f, 0x20, 0x1e,
	0x21, 0xa4, 0xb3, 0x30, 0x11, 0x70, 0x2a, 0x12, 0xd6, 0xbe, 0xd1, 0x73, 0x06, 0xfb, 0xc3, 0x0e,
	0xc9, 0x1d, 0x13, 0xeb, 0x98, 0x9c, 0x5a, 0xc7, 0xc7, 0x7b, 0x97, 0x3f, 0xba, 0xb5, 0x8b, 0x9f,
	0x5d, 0x27, 0xd8, 0xd0, 0xe1, 0x57, 0xa8, 0xb5, 0x90, 0x20, 0xd2, 0x31, 0x50, 0x95, 0x93, 0x6e,
	0xee, 0x40, 0xfa, 0x47, 0x8b, 0x5f, 0xa2, 0x03, 0x53, 0xe1, 0x2f, 0xd2, 0xc8, 0xc0, 0x9a, 0x3b,
	0xc0, 0xca, 0x52, 0xef, 0x1d, 0xba, 0x53, 0x1a, 0x41, 0x31, 0x96, 0x80, 0x7d, 0xce, 0x98, 0x06,
	0x3c, 0x44, 0x87, 0xc5, 0xc0, 0x5f, 0x4f, 0x61, 0x23, 0x8c, 0x3c, 0xab, 0xca, 0x9e, 0xf7, 0xd5,
	0xa9, 0x8e, 0xdb, 0x4e, 0x17, 0xf7, 0xd1, 0x41, 0x5a, 0x41, 0x2b, 0x17, 0xf1, 0x09, 0x6a, 0x6a,
	0xa0, 0x90, 0x69, 0x93, 0x7c, 0x6b, 0xf8, 0x60, 0x8b, 0x50, 0xed, 0x2f, 0xc6, 0x46, 0x18, 0x14,
	0x00, 0xef, 0x11, 0xf2, 0x9e, 0x4d, 0x40, 0x2c, 0xd8, 0x48, 0xe8, 0x98, 0x86, 0xdb, 0xdd, 0x42,
	0xef, 0x09, 0xea, 0x9f, 0xa4, 0xd4, 0xea, 0xb6, 0xbe, 0xbd, 0xc7, 0x6f, 0x2e, 0x57, 0xae, 0x73,
	0xb5, 0x72, 0x9d, 0x5f, 0x2b, 0xd7, 0xb9, 0x58, 0xbb, 0xb5, 0xab, 0xb5, 0x5b, 0xfb, 0xbe, 0x76,
	0x6b, 0x1f, 0x1e, 0x73, 0x01, 0xb3, 0x2c, 0x24, 0x13, 0x99, 0xf8, 0x25, 0x33, 0xbe, 0x16, 0xcb,
	0xfb, 0xd6, 0x8d, 0xbf, 0xf4, 0xed, 0x2b, 0x84, 0xf3, 0x39, 0xd3, 0x61, 0xd3, 0x74, 0x1e, 0xfe,
	0x0e, 0x00, 0x00, 0xff, 0xff, 0x75, 0xb7, 0xf5, 0x85, 0xe6, 0x03, 0x00, 0x00,
}

func (m *DisableVirtualSchemaProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DisableVirtualSchemaProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DisableVirtualSchemaProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.VotingEndTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.VotingEndTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintDisableVirtualSchema(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x32
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.VotinStartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.VotinStartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintDisableVirtualSchema(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	n3, err3 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.SubmitTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.SubmitTime):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintDisableVirtualSchema(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x22
	if len(m.Registry) > 0 {
		for iNdEx := len(m.Registry) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Registry[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDisableVirtualSchema(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.VirtualSchemaCode) > 0 {
		i -= len(m.VirtualSchemaCode)
		copy(dAtA[i:], m.VirtualSchemaCode)
		i = encodeVarintDisableVirtualSchema(dAtA, i, uint64(len(m.VirtualSchemaCode)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintDisableVirtualSchema(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VirtualSchemaDisableRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VirtualSchemaDisableRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VirtualSchemaDisableRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VirtualNftSchemaCode) > 0 {
		i -= len(m.VirtualNftSchemaCode)
		copy(dAtA[i:], m.VirtualNftSchemaCode)
		i = encodeVarintDisableVirtualSchema(dAtA, i, uint64(len(m.VirtualNftSchemaCode)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DisableVirtualSchemaRegistry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DisableVirtualSchemaRegistry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DisableVirtualSchemaRegistry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintDisableVirtualSchema(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.NftSchemaCode) > 0 {
		i -= len(m.NftSchemaCode)
		copy(dAtA[i:], m.NftSchemaCode)
		i = encodeVarintDisableVirtualSchema(dAtA, i, uint64(len(m.NftSchemaCode)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ActiveDislabeVirtualSchemaProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActiveDislabeVirtualSchemaProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActiveDislabeVirtualSchemaProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintDisableVirtualSchema(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InactiveDisableVirtualSchemaProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InactiveDisableVirtualSchemaProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InactiveDisableVirtualSchemaProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintDisableVirtualSchema(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDisableVirtualSchema(dAtA []byte, offset int, v uint64) int {
	offset -= sovDisableVirtualSchema(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DisableVirtualSchemaProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovDisableVirtualSchema(uint64(l))
	}
	l = len(m.VirtualSchemaCode)
	if l > 0 {
		n += 1 + l + sovDisableVirtualSchema(uint64(l))
	}
	if len(m.Registry) > 0 {
		for _, e := range m.Registry {
			l = e.Size()
			n += 1 + l + sovDisableVirtualSchema(uint64(l))
		}
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.SubmitTime)
	n += 1 + l + sovDisableVirtualSchema(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.VotinStartTime)
	n += 1 + l + sovDisableVirtualSchema(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.VotingEndTime)
	n += 1 + l + sovDisableVirtualSchema(uint64(l))
	return n
}

func (m *VirtualSchemaDisableRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VirtualNftSchemaCode)
	if l > 0 {
		n += 1 + l + sovDisableVirtualSchema(uint64(l))
	}
	return n
}

func (m *DisableVirtualSchemaRegistry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NftSchemaCode)
	if l > 0 {
		n += 1 + l + sovDisableVirtualSchema(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovDisableVirtualSchema(uint64(m.Status))
	}
	return n
}

func (m *ActiveDislabeVirtualSchemaProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovDisableVirtualSchema(uint64(l))
	}
	return n
}

func (m *InactiveDisableVirtualSchemaProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovDisableVirtualSchema(uint64(l))
	}
	return n
}

func sovDisableVirtualSchema(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDisableVirtualSchema(x uint64) (n int) {
	return sovDisableVirtualSchema(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DisableVirtualSchemaProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDisableVirtualSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DisableVirtualSchemaProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DisableVirtualSchemaProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VirtualSchemaCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VirtualSchemaCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Registry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Registry = append(m.Registry, &DisableVirtualSchemaRegistry{})
			if err := m.Registry[len(m.Registry)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubmitTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.SubmitTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotinStartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.VotinStartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VotingEndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.VotingEndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDisableVirtualSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VirtualSchemaDisableRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDisableVirtualSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VirtualSchemaDisableRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VirtualSchemaDisableRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VirtualNftSchemaCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VirtualNftSchemaCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDisableVirtualSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DisableVirtualSchemaRegistry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDisableVirtualSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DisableVirtualSchemaRegistry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DisableVirtualSchemaRegistry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftSchemaCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftSchemaCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= RegistryStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDisableVirtualSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActiveDislabeVirtualSchemaProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDisableVirtualSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActiveDislabeVirtualSchemaProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActiveDislabeVirtualSchemaProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDisableVirtualSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InactiveDisableVirtualSchemaProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDisableVirtualSchema
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InactiveDisableVirtualSchemaProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InactiveDisableVirtualSchemaProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDisableVirtualSchema(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDisableVirtualSchema
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDisableVirtualSchema(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDisableVirtualSchema
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDisableVirtualSchema
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDisableVirtualSchema
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDisableVirtualSchema
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDisableVirtualSchema
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDisableVirtualSchema        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDisableVirtualSchema          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDisableVirtualSchema = fmt.Errorf("proto: unexpected end of group")
)
