// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nftmngr/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the nftmngr module's genesis state.
type GenesisState struct {
	Params                  Params                `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	NFTSchemaList           []NFTSchema           `protobuf:"bytes,2,rep,name=nFTSchemaList,proto3" json:"nFTSchemaList"`
	NftDataList             []NftData             `protobuf:"bytes,3,rep,name=nftDataList,proto3" json:"nftDataList"`
	ActionByRefIdList       []ActionByRefId       `protobuf:"bytes,4,rep,name=actionByRefIdList,proto3" json:"actionByRefIdList"`
	OrganizationList        []Organization        `protobuf:"bytes,5,rep,name=organizationList,proto3" json:"organizationList"`
	NFTSchemaByContractList []NFTSchemaByContract `protobuf:"bytes,7,rep,name=nFTSchemaByContractList,proto3" json:"nFTSchemaByContractList"`
	NftFeeConfig            *NFTFeeConfig         `protobuf:"bytes,8,opt,name=nft_fee_config,json=nftFeeConfig,proto3" json:"nft_fee_config,omitempty"`
	NFTFeeBalance           *NFTFeeBalance        `protobuf:"bytes,9,opt,name=nFTFeeBalance,proto3" json:"nFTFeeBalance,omitempty"`
	MetadataCreatorList     []MetadataCreator     `protobuf:"bytes,10,rep,name=metadataCreatorList,proto3" json:"metadataCreatorList"`
	NftCollectionList       []NftCollection       `protobuf:"bytes,11,rep,name=nftCollectionList,proto3" json:"nftCollectionList"`
	ActionExecutorList      []ActionExecutor      `protobuf:"bytes,12,rep,name=actionExecutorList,proto3" json:"actionExecutorList"`
	SchemaAttributeList     []SchemaAttribute     `protobuf:"bytes,13,rep,name=schemaAttributeList,proto3" json:"schemaAttributeList"`
	ActionOfSchemaList      []ActionOfSchema      `protobuf:"bytes,14,rep,name=actionOfSchemaList,proto3" json:"actionOfSchemaList"`
	ExecutorOfSchemaList    []ExecutorOfSchema    `protobuf:"bytes,15,rep,name=executorOfSchemaList,proto3" json:"executorOfSchemaList"`
	VirtualActionList       []VirtualAction       `protobuf:"bytes,16,rep,name=virtualActionList,proto3" json:"virtualActionList"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c26d098aac64c1a, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetNFTSchemaList() []NFTSchema {
	if m != nil {
		return m.NFTSchemaList
	}
	return nil
}

func (m *GenesisState) GetNftDataList() []NftData {
	if m != nil {
		return m.NftDataList
	}
	return nil
}

func (m *GenesisState) GetActionByRefIdList() []ActionByRefId {
	if m != nil {
		return m.ActionByRefIdList
	}
	return nil
}

func (m *GenesisState) GetOrganizationList() []Organization {
	if m != nil {
		return m.OrganizationList
	}
	return nil
}

func (m *GenesisState) GetNFTSchemaByContractList() []NFTSchemaByContract {
	if m != nil {
		return m.NFTSchemaByContractList
	}
	return nil
}

func (m *GenesisState) GetNftFeeConfig() *NFTFeeConfig {
	if m != nil {
		return m.NftFeeConfig
	}
	return nil
}

func (m *GenesisState) GetNFTFeeBalance() *NFTFeeBalance {
	if m != nil {
		return m.NFTFeeBalance
	}
	return nil
}

func (m *GenesisState) GetMetadataCreatorList() []MetadataCreator {
	if m != nil {
		return m.MetadataCreatorList
	}
	return nil
}

func (m *GenesisState) GetNftCollectionList() []NftCollection {
	if m != nil {
		return m.NftCollectionList
	}
	return nil
}

func (m *GenesisState) GetActionExecutorList() []ActionExecutor {
	if m != nil {
		return m.ActionExecutorList
	}
	return nil
}

func (m *GenesisState) GetSchemaAttributeList() []SchemaAttribute {
	if m != nil {
		return m.SchemaAttributeList
	}
	return nil
}

func (m *GenesisState) GetActionOfSchemaList() []ActionOfSchema {
	if m != nil {
		return m.ActionOfSchemaList
	}
	return nil
}

func (m *GenesisState) GetExecutorOfSchemaList() []ExecutorOfSchema {
	if m != nil {
		return m.ExecutorOfSchemaList
	}
	return nil
}

func (m *GenesisState) GetVirtualActionList() []VirtualAction {
	if m != nil {
		return m.VirtualActionList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "thesixnetwork.sixprotocol.nftmngr.GenesisState")
}

func init() { proto.RegisterFile("nftmngr/genesis.proto", fileDescriptor_0c26d098aac64c1a) }

var fileDescriptor_0c26d098aac64c1a = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0x41, 0x4f, 0x13, 0x4f,
	0x18, 0xc6, 0xdb, 0x3f, 0xfc, 0x51, 0xa7, 0x80, 0x38, 0xa2, 0x36, 0x8d, 0xac, 0x68, 0x3c, 0xa0,
	0xd1, 0x2e, 0x42, 0xf4, 0x4e, 0x2b, 0x10, 0x13, 0x05, 0x53, 0x94, 0x18, 0x2f, 0x9b, 0xe9, 0x76,
	0x76, 0x19, 0xed, 0xce, 0x90, 0xdd, 0xb7, 0xd8, 0xfa, 0x29, 0xfc, 0x58, 0x1c, 0x39, 0x1a, 0x0f,
	0xc6, 0xc0, 0x17, 0x31, 0x3b, 0x3b, 0xb3, 0x9d, 0xed, 0x96, 0x38, 0xdc, 0x60, 0xde, 0x79, 0x7e,
	0xcf, 0xcc, 0xbb, 0xcf, 0xbc, 0x45, 0x77, 0x78, 0x00, 0x11, 0x0f, 0x63, 0x37, 0xa4, 0x9c, 0x26,
	0x2c, 0x69, 0x1e, 0xc7, 0x02, 0x04, 0x7e, 0x08, 0x47, 0x34, 0x61, 0x43, 0x4e, 0xe1, 0x9b, 0x88,
	0xbf, 0x36, 0x13, 0x36, 0x94, 0xeb, 0xbe, 0xe8, 0x37, 0x95, 0xa0, 0xb1, 0x1c, 0x8a, 0x50, 0xc8,
	0x55, 0x37, 0xfd, 0x2b, 0x13, 0x36, 0x96, 0x35, 0xef, 0x98, 0xc4, 0x24, 0x52, 0xb8, 0x46, 0x5d,
	0xaf, 0xf2, 0x00, 0xbc, 0xc4, 0x3f, 0xa2, 0x11, 0x51, 0x95, 0xbb, 0x66, 0xa5, 0x47, 0x40, 0xaf,
	0x3b, 0x7a, 0x9d, 0xf8, 0xc0, 0x04, 0xf7, 0xba, 0x23, 0x2f, 0xa6, 0x81, 0xc7, 0x7a, 0xaa, 0xde,
	0xd0, 0x75, 0x11, 0x87, 0x84, 0xb3, 0xef, 0x24, 0xdd, 0xa5, 0x6a, 0x8f, 0xcb, 0x6e, 0xa9, 0xde,
	0x17, 0x1c, 0x62, 0xe2, 0x83, 0xda, 0x75, 0xdf, 0xdc, 0x15, 0x50, 0x9a, 0xd6, 0x03, 0x16, 0xaa,
	0xea, 0xca, 0x64, 0xb5, 0x4b, 0xfa, 0x84, 0xfb, 0x74, 0xf2, 0x78, 0x11, 0x05, 0x92, 0x1e, 0xdb,
	0xf3, 0x63, 0x4a, 0x40, 0xc4, 0xd3, 0xe0, 0xbe, 0xe8, 0xf7, 0xa9, 0x6f, 0x1c, 0x70, 0x65, 0xe2,
	0x72, 0x74, 0x48, 0xfd, 0xc1, 0x58, 0x9c, 0xc3, 0xd5, 0xd9, 0x09, 0x40, 0xcc, 0xba, 0x03, 0xa0,
	0x97, 0xf4, 0x46, 0x04, 0xc5, 0x9e, 0xae, 0xea, 0xba, 0xe6, 0x96, 0x76, 0xe4, 0xc7, 0x3b, 0x61,
	0x31, 0x0c, 0x48, 0xdf, 0x23, 0xc6, 0xf1, 0x1e, 0xfd, 0xaa, 0xa1, 0xf9, 0xdd, 0x2c, 0x0e, 0x07,
	0x40, 0x80, 0xe2, 0x5d, 0x34, 0x97, 0x7d, 0xce, 0x7a, 0x75, 0xb5, 0xba, 0x56, 0xdb, 0x78, 0xd2,
	0xfc, 0x67, 0x3c, 0x9a, 0xef, 0xa5, 0xa0, 0x35, 0x7b, 0xfa, 0xfb, 0x41, 0xa5, 0xa3, 0xe4, 0xf8,
	0x13, 0x5a, 0xe0, 0x3b, 0x1f, 0x0e, 0xe4, 0x51, 0xde, 0xb2, 0x04, 0xea, 0xff, 0xad, 0xce, 0xac,
	0xd5, 0x36, 0x9e, 0x59, 0xf0, 0xf6, 0xb4, 0x4e, 0x21, 0x8b, 0x20, 0xdc, 0x41, 0x35, 0x1e, 0xc0,
	0x6b, 0x02, 0x19, 0x77, 0x46, 0x72, 0x9f, 0xda, 0x70, 0x33, 0x95, 0xa2, 0x9a, 0x10, 0xdc, 0x43,
	0xb7, 0xb2, 0xbe, 0xb4, 0x46, 0x1d, 0x1a, 0xbc, 0xe9, 0x49, 0xf2, 0xac, 0x24, 0xaf, 0x5b, 0x90,
	0xb7, 0x4c, 0xad, 0xe2, 0x97, 0x81, 0x98, 0xa0, 0x25, 0x33, 0xc3, 0xd2, 0xe4, 0x7f, 0x69, 0xe2,
	0x5a, 0x98, 0xec, 0x1b, 0x52, 0xe5, 0x51, 0xc2, 0xe1, 0x13, 0x74, 0x2f, 0xef, 0x56, 0x6b, 0xd4,
	0x56, 0xef, 0x40, 0x3a, 0x5d, 0x93, 0x4e, 0xaf, 0xae, 0xf4, 0x01, 0x72, 0x82, 0x32, 0xbc, 0x0c,
	0x8e, 0x3f, 0xa2, 0xc5, 0xe2, 0xe3, 0xaa, 0x5f, 0x97, 0xf9, 0x71, 0xed, 0xec, 0x76, 0x28, 0x6d,
	0x4b, 0x59, 0x67, 0x9e, 0x07, 0x90, 0xff, 0x87, 0x0f, 0x65, 0x8a, 0x76, 0x28, 0x6d, 0x65, 0x6f,
	0xb2, 0x7e, 0x43, 0x52, 0xd7, 0xad, 0xa9, 0x4a, 0xd7, 0x29, 0x62, 0xf0, 0x17, 0x74, 0x5b, 0x3f,
	0xe7, 0x76, 0xf6, 0x9a, 0x65, 0x8b, 0x90, 0x6c, 0xd1, 0x86, 0x05, 0xfd, 0x5d, 0x51, 0xad, 0xda,
	0x33, 0x0d, 0x9a, 0x66, 0x8b, 0x07, 0xd0, 0xce, 0x27, 0x83, 0x74, 0xaa, 0x59, 0x67, 0x6b, 0xcf,
	0xd4, 0xea, 0x6c, 0x95, 0x80, 0x38, 0x44, 0x38, 0x0b, 0xdc, 0xb6, 0x9a, 0x04, 0xd2, 0x66, 0x5e,
	0xda, 0xbc, 0xb0, 0x8e, 0xb0, 0x16, 0x2b, 0x9f, 0x29, 0xc8, 0xb4, 0x75, 0xd9, 0x80, 0xd9, 0xd2,
	0xb3, 0x4a, 0x3a, 0x2d, 0x58, 0xb7, 0xee, 0xa0, 0xa8, 0xd6, 0xad, 0x9b, 0x02, 0x1d, 0x5f, 0x6a,
	0x3f, 0x30, 0x26, 0xc9, 0xe2, 0x15, 0x2f, 0xa5, 0xc5, 0xc5, 0x4b, 0x99, 0x48, 0x1c, 0xa1, 0x65,
	0x3d, 0x41, 0x0b, 0x56, 0x37, 0xa5, 0xd5, 0xa6, 0x85, 0xd5, 0xf6, 0x84, 0x5c, 0x99, 0x4d, 0xc5,
	0xa6, 0x91, 0x50, 0xe3, 0x78, 0x6b, 0x1c, 0x89, 0x25, 0xeb, 0x48, 0x1c, 0x9a, 0x5a, 0x1d, 0x89,
	0x12, 0xb0, 0xb5, 0x7f, 0x7a, 0xee, 0x54, 0xcf, 0xce, 0x9d, 0xea, 0x9f, 0x73, 0xa7, 0xfa, 0xe3,
	0xc2, 0xa9, 0x9c, 0x5d, 0x38, 0x95, 0x9f, 0x17, 0x4e, 0xe5, 0xf3, 0xcb, 0x90, 0xc1, 0xd1, 0xa0,
	0xdb, 0xf4, 0x45, 0xe4, 0x16, 0xec, 0xdc, 0x84, 0x0d, 0x9f, 0x6b, 0x3f, 0x77, 0xe8, 0xea, 0x1f,
	0x0f, 0x18, 0x1d, 0xd3, 0xa4, 0x3b, 0x27, 0x2b, 0x9b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x1c,
	0x9f, 0xb4, 0x82, 0x4a, 0x08, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VirtualActionList) > 0 {
		for iNdEx := len(m.VirtualActionList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VirtualActionList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1
			i--
			dAtA[i] = 0x82
		}
	}
	if len(m.ExecutorOfSchemaList) > 0 {
		for iNdEx := len(m.ExecutorOfSchemaList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ExecutorOfSchemaList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x7a
		}
	}
	if len(m.ActionOfSchemaList) > 0 {
		for iNdEx := len(m.ActionOfSchemaList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActionOfSchemaList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	if len(m.SchemaAttributeList) > 0 {
		for iNdEx := len(m.SchemaAttributeList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SchemaAttributeList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.ActionExecutorList) > 0 {
		for iNdEx := len(m.ActionExecutorList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActionExecutorList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if len(m.NftCollectionList) > 0 {
		for iNdEx := len(m.NftCollectionList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NftCollectionList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.MetadataCreatorList) > 0 {
		for iNdEx := len(m.MetadataCreatorList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MetadataCreatorList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.NFTFeeBalance != nil {
		{
			size, err := m.NFTFeeBalance.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.NftFeeConfig != nil {
		{
			size, err := m.NftFeeConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if len(m.NFTSchemaByContractList) > 0 {
		for iNdEx := len(m.NFTSchemaByContractList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NFTSchemaByContractList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.OrganizationList) > 0 {
		for iNdEx := len(m.OrganizationList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OrganizationList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ActionByRefIdList) > 0 {
		for iNdEx := len(m.ActionByRefIdList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActionByRefIdList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.NftDataList) > 0 {
		for iNdEx := len(m.NftDataList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NftDataList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.NFTSchemaList) > 0 {
		for iNdEx := len(m.NFTSchemaList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NFTSchemaList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.NFTSchemaList) > 0 {
		for _, e := range m.NFTSchemaList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.NftDataList) > 0 {
		for _, e := range m.NftDataList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ActionByRefIdList) > 0 {
		for _, e := range m.ActionByRefIdList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OrganizationList) > 0 {
		for _, e := range m.OrganizationList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.NFTSchemaByContractList) > 0 {
		for _, e := range m.NFTSchemaByContractList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.NftFeeConfig != nil {
		l = m.NftFeeConfig.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.NFTFeeBalance != nil {
		l = m.NFTFeeBalance.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.MetadataCreatorList) > 0 {
		for _, e := range m.MetadataCreatorList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.NftCollectionList) > 0 {
		for _, e := range m.NftCollectionList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ActionExecutorList) > 0 {
		for _, e := range m.ActionExecutorList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SchemaAttributeList) > 0 {
		for _, e := range m.SchemaAttributeList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ActionOfSchemaList) > 0 {
		for _, e := range m.ActionOfSchemaList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ExecutorOfSchemaList) > 0 {
		for _, e := range m.ExecutorOfSchemaList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.VirtualActionList) > 0 {
		for _, e := range m.VirtualActionList {
			l = e.Size()
			n += 2 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NFTSchemaList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NFTSchemaList = append(m.NFTSchemaList, NFTSchema{})
			if err := m.NFTSchemaList[len(m.NFTSchemaList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftDataList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftDataList = append(m.NftDataList, NftData{})
			if err := m.NftDataList[len(m.NftDataList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionByRefIdList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionByRefIdList = append(m.ActionByRefIdList, ActionByRefId{})
			if err := m.ActionByRefIdList[len(m.ActionByRefIdList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrganizationList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrganizationList = append(m.OrganizationList, Organization{})
			if err := m.OrganizationList[len(m.OrganizationList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NFTSchemaByContractList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NFTSchemaByContractList = append(m.NFTSchemaByContractList, NFTSchemaByContract{})
			if err := m.NFTSchemaByContractList[len(m.NFTSchemaByContractList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftFeeConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NftFeeConfig == nil {
				m.NftFeeConfig = &NFTFeeConfig{}
			}
			if err := m.NftFeeConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NFTFeeBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NFTFeeBalance == nil {
				m.NFTFeeBalance = &NFTFeeBalance{}
			}
			if err := m.NFTFeeBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataCreatorList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataCreatorList = append(m.MetadataCreatorList, MetadataCreator{})
			if err := m.MetadataCreatorList[len(m.MetadataCreatorList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftCollectionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftCollectionList = append(m.NftCollectionList, NftCollection{})
			if err := m.NftCollectionList[len(m.NftCollectionList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionExecutorList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionExecutorList = append(m.ActionExecutorList, ActionExecutor{})
			if err := m.ActionExecutorList[len(m.ActionExecutorList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaAttributeList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SchemaAttributeList = append(m.SchemaAttributeList, SchemaAttribute{})
			if err := m.SchemaAttributeList[len(m.SchemaAttributeList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionOfSchemaList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionOfSchemaList = append(m.ActionOfSchemaList, ActionOfSchema{})
			if err := m.ActionOfSchemaList[len(m.ActionOfSchemaList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutorOfSchemaList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExecutorOfSchemaList = append(m.ExecutorOfSchemaList, ExecutorOfSchema{})
			if err := m.ExecutorOfSchemaList[len(m.ExecutorOfSchemaList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VirtualActionList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VirtualActionList = append(m.VirtualActionList, VirtualAction{})
			if err := m.VirtualActionList[len(m.VirtualActionList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
