// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sixprotocol/nftoracle/action_signer_config.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ActionSignerConfig struct {
	Chain           string `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	ContractAddress string `protobuf:"bytes,2,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	Creator         string `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *ActionSignerConfig) Reset()         { *m = ActionSignerConfig{} }
func (m *ActionSignerConfig) String() string { return proto.CompactTextString(m) }
func (*ActionSignerConfig) ProtoMessage()    {}
func (*ActionSignerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_836752e6643531ff, []int{0}
}
func (m *ActionSignerConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActionSignerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActionSignerConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActionSignerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionSignerConfig.Merge(m, src)
}
func (m *ActionSignerConfig) XXX_Size() int {
	return m.Size()
}
func (m *ActionSignerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionSignerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ActionSignerConfig proto.InternalMessageInfo

func (m *ActionSignerConfig) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *ActionSignerConfig) GetContractAddress() string {
	if m != nil {
		return m.ContractAddress
	}
	return ""
}

func (m *ActionSignerConfig) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*ActionSignerConfig)(nil), "sixprotocol.nftoracle.ActionSignerConfig")
}

func init() {
	proto.RegisterFile("sixprotocol/nftoracle/action_signer_config.proto", fileDescriptor_836752e6643531ff)
}

var fileDescriptor_836752e6643531ff = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xcf, 0xb1, 0x4a, 0x03, 0x41,
	0x10, 0x06, 0xe0, 0x5b, 0x45, 0xc5, 0x6d, 0x84, 0x45, 0xe1, 0xaa, 0x45, 0xac, 0xd2, 0x78, 0x27,
	0x58, 0x58, 0x47, 0x9f, 0x40, 0xed, 0x6c, 0xc2, 0x66, 0xb2, 0xb9, 0x1b, 0x8c, 0x33, 0x61, 0x76,
	0xc4, 0xf5, 0x2d, 0x7c, 0x2c, 0xcb, 0x94, 0x96, 0x72, 0xf7, 0x22, 0xc2, 0x8a, 0x21, 0x58, 0xce,
	0xfc, 0xff, 0x57, 0xfc, 0xf6, 0x2a, 0x61, 0x5e, 0x0b, 0x2b, 0x03, 0xaf, 0x5a, 0x5a, 0x2a, 0x4b,
	0x80, 0x55, 0x6c, 0x03, 0x28, 0x32, 0xcd, 0x12, 0x76, 0x14, 0x65, 0x06, 0x4c, 0x4b, 0xec, 0x9a,
	0xd2, 0x73, 0x67, 0x3b, 0xa2, 0xd9, 0x8a, 0x0b, 0xb2, 0x6e, 0x5a, 0xd0, 0x63, 0x31, 0x77, 0x85,
	0xb8, 0x53, 0x7b, 0x00, 0x7d, 0x40, 0xaa, 0xcd, 0xb9, 0x99, 0x1c, 0x3f, 0xfc, 0x1e, 0x6e, 0x62,
	0x4f, 0x80, 0x49, 0x25, 0x80, 0x4e, 0x17, 0x0b, 0x89, 0x29, 0xd5, 0x7b, 0x25, 0xff, 0xff, 0x76,
	0xb5, 0x3d, 0x02, 0x89, 0x41, 0x59, 0xea, 0xfd, 0xd2, 0xf8, 0x3b, 0x6f, 0xef, 0x3f, 0x07, 0x6f,
	0x36, 0x83, 0x37, 0xdf, 0x83, 0x37, 0x1f, 0xa3, 0xaf, 0x36, 0xa3, 0xaf, 0xbe, 0x46, 0x5f, 0x3d,
	0xdd, 0x74, 0xa8, 0xfd, 0xeb, 0xbc, 0x01, 0x7e, 0x69, 0xb5, 0x8f, 0x09, 0x33, 0x45, 0x7d, 0x63,
	0x79, 0x6e, 0x13, 0xe6, 0xcb, 0xed, 0xd8, 0xbc, 0x33, 0x57, 0xdf, 0xd7, 0x31, 0xcd, 0x0f, 0x4b,
	0x76, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xb8, 0x90, 0xb3, 0x14, 0x01, 0x00, 0x00,
}

func (m *ActionSignerConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActionSignerConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActionSignerConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintActionSignerConfig(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintActionSignerConfig(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintActionSignerConfig(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintActionSignerConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovActionSignerConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ActionSignerConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovActionSignerConfig(uint64(l))
	}
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovActionSignerConfig(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovActionSignerConfig(uint64(l))
	}
	return n
}

func sovActionSignerConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozActionSignerConfig(x uint64) (n int) {
	return sovActionSignerConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ActionSignerConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActionSignerConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActionSignerConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActionSignerConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActionSignerConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActionSignerConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActionSignerConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActionSignerConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActionSignerConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActionSignerConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActionSignerConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActionSignerConfig
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActionSignerConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActionSignerConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActionSignerConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipActionSignerConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowActionSignerConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActionSignerConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActionSignerConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthActionSignerConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupActionSignerConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthActionSignerConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthActionSignerConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowActionSignerConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupActionSignerConfig = fmt.Errorf("proto: unexpected end of group")
)
