// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sixprotocol/nftoracle/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the nftoracle module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params                      Params                   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	MintRequestList             []MintRequest            `protobuf:"bytes,2,rep,name=mintRequestList,proto3" json:"mintRequestList"`
	MintRequestCount            uint64                   `protobuf:"varint,3,opt,name=mintRequestCount,proto3" json:"mintRequestCount,omitempty"`
	ActionRequestList           []ActionOracleRequest    `protobuf:"bytes,4,rep,name=actionRequestList,proto3" json:"actionRequestList"`
	ActionRequestCount          uint64                   `protobuf:"varint,5,opt,name=actionRequestCount,proto3" json:"actionRequestCount,omitempty"`
	CollectionOwnerRequestList  []CollectionOwnerRequest `protobuf:"bytes,6,rep,name=collectionOwnerRequestList,proto3" json:"collectionOwnerRequestList"`
	CollectionOwnerRequestCount uint64                   `protobuf:"varint,7,opt,name=collectionOwnerRequestCount,proto3" json:"collectionOwnerRequestCount,omitempty"`
	OracleConfig                *OracleConfig            `protobuf:"bytes,8,opt,name=oracle_config,json=oracleConfig,proto3" json:"oracle_config,omitempty"`
	ActionSignerList            []ActionSigner           `protobuf:"bytes,9,rep,name=actionSignerList,proto3" json:"actionSignerList"`
	BindedSignerList            []BindedSigner           `protobuf:"bytes,10,rep,name=bindedSignerList,proto3" json:"bindedSignerList"`
	ActionSignerConfigList      []ActionSignerConfig     `protobuf:"bytes,13,rep,name=actionSignerConfigList,proto3" json:"actionSignerConfigList"`
	SyncActionSignerList        []SyncActionSigner       `protobuf:"bytes,14,rep,name=syncActionSignerList,proto3" json:"syncActionSignerList"`
	SyncActionSignerCount       uint64                   `protobuf:"varint,15,opt,name=syncActionSignerCount,proto3" json:"syncActionSignerCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_7bf600921c7714ee, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetMintRequestList() []MintRequest {
	if m != nil {
		return m.MintRequestList
	}
	return nil
}

func (m *GenesisState) GetMintRequestCount() uint64 {
	if m != nil {
		return m.MintRequestCount
	}
	return 0
}

func (m *GenesisState) GetActionRequestList() []ActionOracleRequest {
	if m != nil {
		return m.ActionRequestList
	}
	return nil
}

func (m *GenesisState) GetActionRequestCount() uint64 {
	if m != nil {
		return m.ActionRequestCount
	}
	return 0
}

func (m *GenesisState) GetCollectionOwnerRequestList() []CollectionOwnerRequest {
	if m != nil {
		return m.CollectionOwnerRequestList
	}
	return nil
}

func (m *GenesisState) GetCollectionOwnerRequestCount() uint64 {
	if m != nil {
		return m.CollectionOwnerRequestCount
	}
	return 0
}

func (m *GenesisState) GetOracleConfig() *OracleConfig {
	if m != nil {
		return m.OracleConfig
	}
	return nil
}

func (m *GenesisState) GetActionSignerList() []ActionSigner {
	if m != nil {
		return m.ActionSignerList
	}
	return nil
}

func (m *GenesisState) GetBindedSignerList() []BindedSigner {
	if m != nil {
		return m.BindedSignerList
	}
	return nil
}

func (m *GenesisState) GetActionSignerConfigList() []ActionSignerConfig {
	if m != nil {
		return m.ActionSignerConfigList
	}
	return nil
}

func (m *GenesisState) GetSyncActionSignerList() []SyncActionSigner {
	if m != nil {
		return m.SyncActionSignerList
	}
	return nil
}

func (m *GenesisState) GetSyncActionSignerCount() uint64 {
	if m != nil {
		return m.SyncActionSignerCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "sixprotocol.nftoracle.GenesisState")
}

func init() {
	proto.RegisterFile("sixprotocol/nftoracle/genesis.proto", fileDescriptor_7bf600921c7714ee)
}

var fileDescriptor_7bf600921c7714ee = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x1b, 0x56, 0xca, 0xe6, 0x6d, 0x6c, 0xb3, 0x36, 0x54, 0x15, 0x11, 0xaa, 0xf6, 0x40,
	0x57, 0x69, 0x09, 0x1a, 0x93, 0xb8, 0x6e, 0xed, 0x01, 0x0e, 0xa0, 0x41, 0x2a, 0x2e, 0x1c, 0xa8,
	0xd2, 0xcc, 0xcb, 0x2c, 0x5a, 0xbb, 0xc4, 0xae, 0xd6, 0x7d, 0x0b, 0xf8, 0x16, 0x1c, 0xf9, 0x18,
	0x3b, 0xee, 0xc8, 0x09, 0xa1, 0xf6, 0xc0, 0xd7, 0x40, 0x79, 0xce, 0x36, 0x27, 0x75, 0xa2, 0x5e,
	0xda, 0xc4, 0xfe, 0xbd, 0xff, 0xfb, 0x3f, 0xbf, 0x17, 0xa3, 0xa6, 0xa0, 0xd3, 0x71, 0xc4, 0x25,
	0x0f, 0xf8, 0xd0, 0x65, 0xe7, 0x92, 0x47, 0x7e, 0x30, 0x24, 0x6e, 0x48, 0x18, 0x11, 0x54, 0x38,
	0xb0, 0x85, 0xf7, 0x34, 0xc8, 0xb9, 0x83, 0x6a, 0x3b, 0xfe, 0x88, 0x32, 0xee, 0xc2, 0xaf, 0x22,
	0x6b, 0xbb, 0x21, 0x0f, 0x39, 0x3c, 0xba, 0xf1, 0x53, 0xb2, 0xda, 0x30, 0x27, 0x19, 0xfb, 0x91,
	0x3f, 0x4a, 0x72, 0xd4, 0x5a, 0x66, 0x66, 0x44, 0x99, 0xec, 0x47, 0xe4, 0xdb, 0x84, 0x08, 0x99,
	0x90, 0x6d, 0x33, 0xe9, 0x07, 0x92, 0x72, 0x96, 0x61, 0x8f, 0xcc, 0x6c, 0xc0, 0x87, 0x43, 0xa2,
	0x78, 0x7e, 0xc9, 0x48, 0x94, 0x89, 0xda, 0x37, 0x47, 0xa9, 0xbf, 0x7e, 0xc0, 0xd9, 0x39, 0x0d,
	0x8b, 0xd1, 0xc4, 0x8c, 0xa0, 0x21, 0x23, 0x51, 0x31, 0x3a, 0xa0, 0xec, 0x8c, 0x9c, 0xa5, 0xd1,
	0x97, 0x4b, 0xa8, 0xa6, 0x7d, 0x38, 0xe6, 0x08, 0x71, 0xc5, 0x82, 0xbe, 0xc1, 0x4c, 0xe3, 0xc7,
	0x2a, 0xda, 0x78, 0xa3, 0x9a, 0xdc, 0x93, 0xbe, 0x24, 0xf8, 0x18, 0x55, 0x54, 0x3f, 0xaa, 0x56,
	0xdd, 0x6a, 0xad, 0x1f, 0x3e, 0x73, 0x8c, 0x4d, 0x77, 0x3e, 0x00, 0xd4, 0x59, 0xbb, 0xfe, 0xf3,
	0xbc, 0xf4, 0xf3, 0xdf, 0xaf, 0xb6, 0xe5, 0x25, 0x71, 0xd8, 0x43, 0x5b, 0x71, 0xb7, 0x3c, 0x75,
	0x94, 0xef, 0xa8, 0x90, 0xd5, 0x07, 0xf5, 0x95, 0xd6, 0xfa, 0x61, 0x23, 0x47, 0xea, 0xfd, 0x3d,
	0xdd, 0x29, 0xc7, 0x7a, 0x5e, 0x56, 0x00, 0xb7, 0xd1, 0xb6, 0xb6, 0xd4, 0xe5, 0x13, 0x26, 0xab,
	0x2b, 0x75, 0xab, 0x55, 0xf6, 0x16, 0xd6, 0xf1, 0x17, 0xb4, 0xa3, 0x2a, 0xd5, 0x1d, 0x94, 0xc1,
	0x41, 0x3b, 0xc7, 0xc1, 0x09, 0xf0, 0xa7, 0xf0, 0x92, 0x76, 0xb2, 0x28, 0x85, 0x1d, 0x84, 0x53,
	0x8b, 0xca, 0xcd, 0x43, 0x70, 0x63, 0xd8, 0xc1, 0x02, 0xd5, 0xee, 0xe7, 0xec, 0x34, 0x1e, 0x33,
	0xdd, 0x58, 0x05, 0x8c, 0x1d, 0xe4, 0x18, 0xeb, 0x1a, 0x03, 0x13, 0x6f, 0x05, 0xb2, 0xf8, 0x18,
	0x3d, 0x35, 0xef, 0x2a, 0xb7, 0x8f, 0xc0, 0x6d, 0x11, 0x82, 0xdf, 0xa2, 0xcd, 0xd4, 0xa0, 0x57,
	0x57, 0x61, 0x1e, 0x9a, 0x39, 0x4e, 0xd5, 0xe1, 0x75, 0x01, 0xf5, 0x36, 0xb8, 0xf6, 0x86, 0x3f,
	0xa1, 0x6d, 0x75, 0x2c, 0x3d, 0x98, 0x3c, 0x28, 0x7b, 0x0d, 0xca, 0x6e, 0x16, 0xf6, 0x43, 0xe1,
	0x49, 0xb1, 0x0b, 0x12, 0xb1, 0xac, 0xfa, 0x66, 0x34, 0x59, 0x54, 0x28, 0xdb, 0xd1, 0xf0, 0x5b,
	0xd9, 0xac, 0x04, 0x0e, 0xd1, 0x13, 0x3d, 0x95, 0xaa, 0x01, 0xc4, 0x37, 0x41, 0x7c, 0x7f, 0x09,
	0xcf, 0x2a, 0x28, 0x49, 0x91, 0x23, 0x87, 0x7d, 0xb4, 0x1b, 0x7f, 0x96, 0x27, 0xd9, 0xa3, 0x79,
	0x0c, 0x69, 0x5e, 0xe4, 0xa4, 0xe9, 0x65, 0x42, 0x92, 0x24, 0x46, 0x29, 0x7c, 0x84, 0xf6, 0xb2,
	0xeb, 0xaa, 0xff, 0x5b, 0xd0, 0x7f, 0xf3, 0x66, 0xe7, 0xe3, 0xf5, 0xcc, 0xb6, 0x6e, 0x66, 0xb6,
	0xf5, 0x77, 0x66, 0x5b, 0xdf, 0xe7, 0x76, 0xe9, 0x66, 0x6e, 0x97, 0x7e, 0xcf, 0xed, 0xd2, 0xe7,
	0xd7, 0x21, 0x95, 0x17, 0x93, 0x81, 0x13, 0xf0, 0x91, 0x2b, 0x2f, 0x88, 0xa0, 0x53, 0x46, 0xe4,
	0x25, 0x8f, 0xbe, 0xba, 0x82, 0x4e, 0x0f, 0xee, 0xee, 0x9d, 0xa9, 0x76, 0xf3, 0xc8, 0xab, 0x31,
	0x11, 0x83, 0x0a, 0xec, 0xbd, 0xfa, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x89, 0x9a, 0x3d, 0x29, 0x67,
	0x06, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SyncActionSignerCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SyncActionSignerCount))
		i--
		dAtA[i] = 0x78
	}
	if len(m.SyncActionSignerList) > 0 {
		for iNdEx := len(m.SyncActionSignerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SyncActionSignerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x72
		}
	}
	if len(m.ActionSignerConfigList) > 0 {
		for iNdEx := len(m.ActionSignerConfigList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActionSignerConfigList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if len(m.BindedSignerList) > 0 {
		for iNdEx := len(m.BindedSignerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BindedSignerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.ActionSignerList) > 0 {
		for iNdEx := len(m.ActionSignerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActionSignerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.OracleConfig != nil {
		{
			size, err := m.OracleConfig.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.CollectionOwnerRequestCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CollectionOwnerRequestCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.CollectionOwnerRequestList) > 0 {
		for iNdEx := len(m.CollectionOwnerRequestList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CollectionOwnerRequestList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.ActionRequestCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ActionRequestCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.ActionRequestList) > 0 {
		for iNdEx := len(m.ActionRequestList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActionRequestList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.MintRequestCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MintRequestCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.MintRequestList) > 0 {
		for iNdEx := len(m.MintRequestList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MintRequestList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.MintRequestList) > 0 {
		for _, e := range m.MintRequestList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.MintRequestCount != 0 {
		n += 1 + sovGenesis(uint64(m.MintRequestCount))
	}
	if len(m.ActionRequestList) > 0 {
		for _, e := range m.ActionRequestList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ActionRequestCount != 0 {
		n += 1 + sovGenesis(uint64(m.ActionRequestCount))
	}
	if len(m.CollectionOwnerRequestList) > 0 {
		for _, e := range m.CollectionOwnerRequestList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CollectionOwnerRequestCount != 0 {
		n += 1 + sovGenesis(uint64(m.CollectionOwnerRequestCount))
	}
	if m.OracleConfig != nil {
		l = m.OracleConfig.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.ActionSignerList) > 0 {
		for _, e := range m.ActionSignerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BindedSignerList) > 0 {
		for _, e := range m.BindedSignerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ActionSignerConfigList) > 0 {
		for _, e := range m.ActionSignerConfigList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SyncActionSignerList) > 0 {
		for _, e := range m.SyncActionSignerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.SyncActionSignerCount != 0 {
		n += 1 + sovGenesis(uint64(m.SyncActionSignerCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintRequestList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintRequestList = append(m.MintRequestList, MintRequest{})
			if err := m.MintRequestList[len(m.MintRequestList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintRequestCount", wireType)
			}
			m.MintRequestCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MintRequestCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionRequestList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionRequestList = append(m.ActionRequestList, ActionOracleRequest{})
			if err := m.ActionRequestList[len(m.ActionRequestList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionRequestCount", wireType)
			}
			m.ActionRequestCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActionRequestCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionOwnerRequestList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CollectionOwnerRequestList = append(m.CollectionOwnerRequestList, CollectionOwnerRequest{})
			if err := m.CollectionOwnerRequestList[len(m.CollectionOwnerRequestList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionOwnerRequestCount", wireType)
			}
			m.CollectionOwnerRequestCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CollectionOwnerRequestCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OracleConfig == nil {
				m.OracleConfig = &OracleConfig{}
			}
			if err := m.OracleConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionSignerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionSignerList = append(m.ActionSignerList, ActionSigner{})
			if err := m.ActionSignerList[len(m.ActionSignerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BindedSignerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BindedSignerList = append(m.BindedSignerList, BindedSigner{})
			if err := m.BindedSignerList[len(m.BindedSignerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActionSignerConfigList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActionSignerConfigList = append(m.ActionSignerConfigList, ActionSignerConfig{})
			if err := m.ActionSignerConfigList[len(m.ActionSignerConfigList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SyncActionSignerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SyncActionSignerList = append(m.SyncActionSignerList, SyncActionSigner{})
			if err := m.SyncActionSignerList[len(m.SyncActionSignerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SyncActionSignerCount", wireType)
			}
			m.SyncActionSignerCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SyncActionSignerCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
