// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: nftoracle/request.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RequestStatus int32

const (
	RequestStatus_PENDING                    RequestStatus = 0
	RequestStatus_SUCCESS_WITH_CONSENSUS     RequestStatus = 1
	RequestStatus_FAILED_WITHOUT_CONCENSUS   RequestStatus = 2
	RequestStatus_EXPIRED                    RequestStatus = 3
	RequestStatus_FAILED_ON_EXECUTION        RequestStatus = 4
	RequestStatus_FAILED_REJECT_BY_CONSENSUS RequestStatus = 5
)

var RequestStatus_name = map[int32]string{
	0: "PENDING",
	1: "SUCCESS_WITH_CONSENSUS",
	2: "FAILED_WITHOUT_CONCENSUS",
	3: "EXPIRED",
	4: "FAILED_ON_EXECUTION",
	5: "FAILED_REJECT_BY_CONSENSUS",
}

var RequestStatus_value = map[string]int32{
	"PENDING":                    0,
	"SUCCESS_WITH_CONSENSUS":     1,
	"FAILED_WITHOUT_CONCENSUS":   2,
	"EXPIRED":                    3,
	"FAILED_ON_EXECUTION":        4,
	"FAILED_REJECT_BY_CONSENSUS": 5,
}

func (x RequestStatus) String() string {
	return proto.EnumName(RequestStatus_name, int32(x))
}

func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f60220a52ce49438, []int{0}
}

type NftOriginData struct {
	Image         string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	HolderAddress string   `protobuf:"bytes,2,opt,name=holder_address,json=holderAddress,proto3" json:"holder_address,omitempty"`
	Traits        []*Trait `protobuf:"bytes,3,rep,name=traits,proto3" json:"traits,omitempty"`
}

func (m *NftOriginData) Reset()         { *m = NftOriginData{} }
func (m *NftOriginData) String() string { return proto.CompactTextString(m) }
func (*NftOriginData) ProtoMessage()    {}
func (*NftOriginData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f60220a52ce49438, []int{0}
}
func (m *NftOriginData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftOriginData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftOriginData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftOriginData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftOriginData.Merge(m, src)
}
func (m *NftOriginData) XXX_Size() int {
	return m.Size()
}
func (m *NftOriginData) XXX_DiscardUnknown() {
	xxx_messageInfo_NftOriginData.DiscardUnknown(m)
}

var xxx_messageInfo_NftOriginData proto.InternalMessageInfo

func (m *NftOriginData) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *NftOriginData) GetHolderAddress() string {
	if m != nil {
		return m.HolderAddress
	}
	return ""
}

func (m *NftOriginData) GetTraits() []*Trait {
	if m != nil {
		return m.Traits
	}
	return nil
}

type DataHash struct {
	OriginData *NftOriginData `protobuf:"bytes,1,opt,name=origin_data,json=originData,proto3" json:"origin_data,omitempty"`
	Hash       []byte         `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Confirmers []string       `protobuf:"bytes,3,rep,name=confirmers,proto3" json:"confirmers,omitempty"`
}

func (m *DataHash) Reset()         { *m = DataHash{} }
func (m *DataHash) String() string { return proto.CompactTextString(m) }
func (*DataHash) ProtoMessage()    {}
func (*DataHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_f60220a52ce49438, []int{1}
}
func (m *DataHash) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataHash.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DataHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataHash.Merge(m, src)
}
func (m *DataHash) XXX_Size() int {
	return m.Size()
}
func (m *DataHash) XXX_DiscardUnknown() {
	xxx_messageInfo_DataHash.DiscardUnknown(m)
}

var xxx_messageInfo_DataHash proto.InternalMessageInfo

func (m *DataHash) GetOriginData() *NftOriginData {
	if m != nil {
		return m.OriginData
	}
	return nil
}

func (m *DataHash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *DataHash) GetConfirmers() []string {
	if m != nil {
		return m.Confirmers
	}
	return nil
}

func init() {
	proto.RegisterEnum("thesixnetwork.sixnft.nftoracle.RequestStatus", RequestStatus_name, RequestStatus_value)
	proto.RegisterType((*NftOriginData)(nil), "thesixnetwork.sixnft.nftoracle.NftOriginData")
	proto.RegisterType((*DataHash)(nil), "thesixnetwork.sixnft.nftoracle.DataHash")
}

func init() { proto.RegisterFile("nftoracle/request.proto", fileDescriptor_f60220a52ce49438) }

var fileDescriptor_f60220a52ce49438 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xb3, 0x4d, 0x5b, 0xe8, 0x86, 0xa0, 0x68, 0x41, 0x34, 0x8a, 0xd0, 0x52, 0x55, 0xaa,
	0x54, 0x21, 0xd5, 0x96, 0xca, 0x81, 0x13, 0x87, 0xd6, 0x59, 0x68, 0x10, 0xb2, 0x8b, 0xed, 0x88,
	0xc2, 0xc5, 0xda, 0x24, 0x6b, 0x7b, 0x45, 0xec, 0x0d, 0xbb, 0x13, 0x11, 0x9e, 0x01, 0x09, 0xf1,
	0x00, 0x3c, 0x10, 0xc7, 0x1e, 0x39, 0xa2, 0xe4, 0x45, 0x90, 0xd7, 0x11, 0x4d, 0x2f, 0x70, 0x9b,
	0x99, 0xff, 0x9f, 0xf1, 0x37, 0x9e, 0xc5, 0xfb, 0x65, 0x0a, 0x4a, 0xf3, 0xf1, 0x54, 0xb8, 0x5a,
	0x7c, 0x9a, 0x0b, 0x03, 0xce, 0x4c, 0x2b, 0x50, 0x84, 0x42, 0x2e, 0x8c, 0x5c, 0x94, 0x02, 0x3e,
	0x2b, 0xfd, 0xd1, 0xa9, 0xc2, 0x14, 0x9c, 0xbf, 0xee, 0xde, 0x46, 0xa3, 0x9a, 0x89, 0xd2, 0x08,
	0x5e, 0x37, 0xf6, 0x9e, 0x64, 0x4a, 0x65, 0x53, 0xe1, 0xda, 0x6c, 0x34, 0x4f, 0x5d, 0x90, 0x85,
	0x30, 0xc0, 0x8b, 0x59, 0x6d, 0x38, 0xfc, 0x8a, 0x70, 0xdb, 0x4f, 0x21, 0xd0, 0x32, 0x93, 0x65,
	0x9f, 0x03, 0x27, 0x0f, 0xf1, 0x8e, 0x2c, 0x78, 0x26, 0xba, 0xe8, 0x00, 0x1d, 0xef, 0x85, 0x75,
	0x42, 0x8e, 0xf0, 0xfd, 0x5c, 0x4d, 0x27, 0x42, 0x27, 0x7c, 0x32, 0xd1, 0xc2, 0x98, 0xee, 0x96,
	0x95, 0xdb, 0x75, 0xf5, 0xac, 0x2e, 0x92, 0x17, 0x78, 0x17, 0x34, 0x97, 0x60, 0xba, 0xcd, 0x83,
	0xe6, 0x71, 0xeb, 0xf4, 0xc8, 0xf9, 0x37, 0xb9, 0x13, 0x57, 0xee, 0x70, 0xdd, 0x74, 0xf8, 0x0d,
	0xe1, 0xbb, 0x15, 0xc4, 0x05, 0x37, 0x39, 0xf1, 0x71, 0x4b, 0x59, 0xac, 0x64, 0xc2, 0x81, 0x5b,
	0x9c, 0xd6, 0xe9, 0xc9, 0xff, 0x06, 0xde, 0x5a, 0x26, 0xc4, 0xea, 0x66, 0x31, 0x82, 0xb7, 0x73,
	0x6e, 0x72, 0x0b, 0x7e, 0x2f, 0xb4, 0x31, 0xa1, 0x18, 0x8f, 0x55, 0x99, 0x4a, 0x5d, 0x08, 0x5d,
	0x33, 0xef, 0x85, 0x1b, 0x95, 0xa7, 0x3f, 0x10, 0x6e, 0x87, 0xf5, 0x29, 0x22, 0xe0, 0x30, 0x37,
	0xa4, 0x85, 0xef, 0x5c, 0x32, 0xbf, 0x3f, 0xf0, 0x5f, 0x75, 0x1a, 0xa4, 0x87, 0x1f, 0x45, 0x43,
	0xcf, 0x63, 0x51, 0x94, 0xbc, 0x1b, 0xc4, 0x17, 0x89, 0x17, 0xf8, 0x11, 0xf3, 0xa3, 0x61, 0xd4,
	0x41, 0xe4, 0x31, 0xee, 0xbe, 0x3c, 0x1b, 0xbc, 0x61, 0x7d, 0x2b, 0x05, 0xc3, 0xb8, 0x52, 0xbd,
	0x5a, 0xdd, 0xaa, 0xc6, 0xb0, 0xab, 0xcb, 0x41, 0xc8, 0xfa, 0x9d, 0x26, 0xd9, 0xc7, 0x0f, 0xd6,
	0xd6, 0xc0, 0x4f, 0xd8, 0x15, 0xf3, 0x86, 0xf1, 0x20, 0xf0, 0x3b, 0xdb, 0x84, 0xe2, 0xde, 0x5a,
	0x08, 0xd9, 0x6b, 0xe6, 0xc5, 0xc9, 0xf9, 0xfb, 0x8d, 0x6f, 0xec, 0x9c, 0xbf, 0xfd, 0xb9, 0xa4,
	0xe8, 0x7a, 0x49, 0xd1, 0xef, 0x25, 0x45, 0xdf, 0x57, 0xb4, 0x71, 0xbd, 0xa2, 0x8d, 0x5f, 0x2b,
	0xda, 0xf8, 0xf0, 0x3c, 0x93, 0x90, 0xcf, 0x47, 0xce, 0x58, 0x15, 0xee, 0xad, 0x3f, 0xe6, 0x1a,
	0xb9, 0x38, 0xb1, 0xb7, 0x1f, 0xab, 0xa9, 0xbb, 0x70, 0x6f, 0x5e, 0x0e, 0x7c, 0x99, 0x09, 0x33,
	0xda, 0xb5, 0xda, 0xb3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xdb, 0x6e, 0xb9, 0x8c, 0x02,
	0x00, 0x00,
}

func (m *NftOriginData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftOriginData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftOriginData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Traits) > 0 {
		for iNdEx := len(m.Traits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Traits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintRequest(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.HolderAddress) > 0 {
		i -= len(m.HolderAddress)
		copy(dAtA[i:], m.HolderAddress)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.HolderAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Image) > 0 {
		i -= len(m.Image)
		copy(dAtA[i:], m.Image)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Image)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DataHash) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataHash) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataHash) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Confirmers) > 0 {
		for iNdEx := len(m.Confirmers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Confirmers[iNdEx])
			copy(dAtA[i:], m.Confirmers[iNdEx])
			i = encodeVarintRequest(dAtA, i, uint64(len(m.Confirmers[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintRequest(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	if m.OriginData != nil {
		{
			size, err := m.OriginData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintRequest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRequest(dAtA []byte, offset int, v uint64) int {
	offset -= sovRequest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NftOriginData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.HolderAddress)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	if len(m.Traits) > 0 {
		for _, e := range m.Traits {
			l = e.Size()
			n += 1 + l + sovRequest(uint64(l))
		}
	}
	return n
}

func (m *DataHash) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OriginData != nil {
		l = m.OriginData.Size()
		n += 1 + l + sovRequest(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovRequest(uint64(l))
	}
	if len(m.Confirmers) > 0 {
		for _, s := range m.Confirmers {
			l = len(s)
			n += 1 + l + sovRequest(uint64(l))
		}
	}
	return n
}

func sovRequest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRequest(x uint64) (n int) {
	return sovRequest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NftOriginData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftOriginData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftOriginData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HolderAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HolderAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Traits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Traits = append(m.Traits, &Trait{})
			if err := m.Traits[len(m.Traits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataHash) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRequest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataHash: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataHash: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OriginData == nil {
				m.OriginData = &NftOriginData{}
			}
			if err := m.OriginData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = append(m.Hash[:0], dAtA[iNdEx:postIndex]...)
			if m.Hash == nil {
				m.Hash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Confirmers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRequest
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRequest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Confirmers = append(m.Confirmers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRequest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRequest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRequest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRequest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRequest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRequest
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRequest
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRequest
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRequest        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRequest          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRequest = fmt.Errorf("proto: unexpected end of group")
)
