name: Sync Wiki

on:
  push:
    paths:
      - 'docs/wiki/**'
    branches:
      - development

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Clone wiki
        run: |
          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/thesixnetwork/six-protocol.wiki.git wiki

      - name: Sync docs to wiki
        run: |
          set -e
          echo "Clearing existing wiki content"
          rm -rf wiki/*
          echo "Copying docs to wiki"
          cp -r docs/wiki/* wiki/ || echo "No files to copy"
          cd wiki
          echo "Adding files to git"
          git add .
          echo "Checking for changes"
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: sync from main repo ${GITHUB_SHA}" && git push)
