name: Sync Wiki

on:
  push:
    paths:
      - 'docs/wiki/**'
    branches:
      - development

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Clone wiki
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/thesixnetwork/six-protocol.wiki.git wiki
      
      - name: Copy doc to wiki
        run: |
          cp -Rv docs/wiki/* wiki/
      
      - name: Commit and push changes
        working-directory: wiki
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "chore: auto-update wiki from docs"
            git push origin master
          else
            echo "No changes to commit"
          fi


